spring:
  output:
    ansi:
      enabled: always

  application:
    name: sbb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


  profiles:
    active: dev

logging:
  level:
    org.hibernate.sql.jdbc.bind: trace

